- hosts: localhost
  connection: local
  gather_facts: no
  sudo: no
  vars:
    homebrew_taps:
      - homebrew/binary
      - homebrew/dupes
      - caskroom/cask
    homebrew_packages:
      - { name: git }
      - { name: tree }
      - { name: openssl }
      - { name: ruby }
      - { name: wget }
      - { name: curl }
      - { name: go }
      - { name: node }
      - { name: zsh, install_options: disable-etcdir }
      - { name: libxml2 }
      - { name: glib }
      - { name: sha2 }
      - { name: mysql }
      - { name: autoconf }
      - { name: nkf }
      - { name: selenium -server-standalone }
      - { name: chromedriver }
      - { name: sqlite }
      - { name: cocot }
      - { name: imagemagick }
      - { name: tig }
      - { name: composer }
      - { name: cvs }
      - { name: libevent }
      - { name: peco }
      - { name: geckodriver }
      - { name: libyaml }
      - { name: gibo }
      - { name: pwgen }
      - { name: python }
      - { name: vim }

    homebrew_cask_packages:
      - { name: iterm2 }
      - { name: firefox }
      - { name: google-chrome }
      - { name: google-japanese-ime }
      - { name: java }
      - { name: slack }
      - { name: virtualbox }
      - { name: vagrant }
      - { name: karabiner }
      - { name: sublime-text }
      - { name: vagrant-manager }
      - { name: docker-toolbox }
      - { name: phpstorm }
      - { name: appcleaner }
      - { name: sourcetree }
      - { name: macs-fan-control }
      - { name: chatwork }
      - { name: mysqlworkbench }
      - { name: clipy }
      - { name: java }
      - { name: skype }
      - { name: visual-studio-code }
      - { name: vagrant }

  tasks:
    - name: homebrew の tap リポジトリを追加
      homebrew_tap: tap={{ item }} state=present
      with_items: homebrew_taps

    - name: homebrew をアップデート
      homebrew: update_homebrew=yes

    # brew
    - name: brew パッケージをインストール
      homebrew: >
        name={{ item.name }}
        state={{ item.state | default('latest') }}
        install_options={{
          item.install_options | default() | join(',')
          if item.install_options is not string
          else item.install_options
        }}
      with_items: homebrew_packages
      register: brew_result
    - name: brew パッケージの情報保存先ディレクトリを作成
      file: path=brew_info state=directory
    - name: brew パッケージの情報を保存
      shell: brew info {{ item }} > brew_info/{{ item }}
      with_items: brew_result.results | selectattr('changed') | map(attribute='item') | map(attribute='name') | list

    # cask
    - name: cask パッケージをインストール
      homebrew_cask: name={{ item.name }} state={{ item.state|default('installed') }}
      environment:
        HOMEBREW_CASK_OPTS: --appdir=/Applications
      with_items: homebrew_cask_packages
      register: cask_result
    - name: cask パッケージの情報保存先ディレクトリを作成
      file: path=cask_info state=directory
    - name: cask パッケージの情報を保存
      shell: brew cask info {{ item }} > cask_info/{{ item }}
      with_items: cask_result.results | selectattr('changed') | map(attribute='item') | map(attribute='name') | list

    # zsh
    - name: .zshrc コピー
      file: src=./.zshrc dest=~/.zshrc

    - name: /bin/zsh にシェルを切り替え
      command: chsh -s /bin/zsh

    # vim
    - name: .vimrc のコピー
      file: src=./vimrc dest=./.vimrc

  handlers:
